### ISSUE TITLE
Mouse cursor

### ISSUE THREAD

**Issue by andygill** [ku-fpg/blank-canvas#31]
Provide a way of changing the mouse counter

 * http://stackoverflow.com/questions/4564251/change-the-mouse-pointer-using-javascript
 * http://stackoverflow.com/questions/17414034/change-mouse-cursor-in-javascript-or-jquery

````
cursor :: Text -> Canvas ()
`````

**Comment by RyanGlScott** [comment]
Added in e1f48414bbf2b72edfe31eb3b508cdf6fde4bf9a.
