### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/blank-canvas#63]
The documentation for many Canvas API functions is lacking or non-existent at the moment. This can be intimidating for beginners, so let's at least add a basic description of what each function does (perhaps using [this overview](http://www.w3schools.com/tags/ref_canvas.asp) of `<canvas>`).

**Comment by RyanGlScott** [comment]
Most of the functions now have a short blurb describing what they do, and many of them now have examples.

**Comment by andygill** [comment]
We do have https://github.com/ku-fpg/blank-canvas/wiki/Canvas-Examples, and https://github.com/ku-fpg/blank-canvas/wiki/API, but I suppose we should at least point to this.

**Comment by RyanGlScott** [comment]
Ah, I suppose I should link to that from the Haddocks as well. I was mostly referencing the descriptions that accompany the functions themselves in `Graphics.Blank`.
