### ISSUE TITLE
release supporting GHC-7.10?

### ISSUE THREAD

**Issue by bergey** [ku-fpg/blank-canvas#69]
Can someone estimate when the version on Hackage will support GHC-7.10?  It looks like HEAD already does, but maybe some upstream packages (`stringsearch`) do not.

We're preparing for a 1.3 Diagrams release, so I'm wondering if the next release of `diagrams-canvas` will be able to support GHC-7.10.

**Comment by jeffreyrosenbluth** [comment]
@andygill 
Hi Andy, any word on this issue.? We are really close to the release of 1.3 and would like diagrams-canvas to be a part of it.

**Comment by andygill** [comment]
Sorry, I missed this. We can work on this over the weekend, if that's okay, and see if we can push something on Sunday?

**Comment by jeffreyrosenbluth** [comment]
Great, I'm sure we can hold out until then.

**Comment by RyanGlScott** [comment]
Belated announcement: [`blank-canvas-0.6`](http://hackage.haskell.org/package/blank-canvas-0.6) fixes this.
