### ISSUE TITLE
How to react on resize

### ISSUE THREAD

**Issue by nomeata** [ku-fpg/blank-canvas#77]
I’m playing around with blank-canvas (actually trying to make it a backend for the API provided on http://code.world/). One thing I wonder: Is there a way to react on window resize requests?

**Comment by RyanGlScott** [comment]
While `blank-canvas` does have a [general mechanism](http://hackage.haskell.org/package/blank-canvas-0.6/docs/Graphics-Blank.html#g:23) for reacting to DOM events through jQuery, it doesn't seem to react to the [`resize`](https://api.jquery.com/resize/) event for reasons that I don't fully understand (it does work for events like `keypress` or `mouseover`).

**Comment by andygill** [comment]
When blank canvas was originally designed, resize event handling was intentionally omitted, because the size is immutable in the Context state. I wanted programmers to be able to depend on this, given the intent that blank canvas is for small (sometimes trivial) examples and teaching. A resize could, however, force a restart of the application. What I do is get the size I want, then press ^R to restart. However, I'm open to alternative designs here, that allow you to code what you as wanting to do.

**Comment by nomeata** [comment]
The problem might be that the `resize` event is only triggered on the `window` object?

I wanted to try this change
```
diff --git a/static/index.html b/static/index.html
index 606a317..d2fc6fe 100644
--- a/static/index.html
+++ b/static/index.html
@@ -123,7 +123,11 @@
             }
 
             function register(name) {
-                $(document).bind(name,Trigger);
+               if (name == 'resize') {
+                       $(window).bind(name,Trigger);
+               } else {
+                       $(document).bind(name,Trigger);
+               };
             }
 
             function redraw() {
```
but I cannot test it easily with HEAD (no remote-monad-0.3 on hackage), and the version 0.6 has no tag in the git repo to conveniently jump to. I’ll try building from the tarball…

**Comment by nomeata** [comment]
> What I do is get the size I want, then press ^R to restart. 

Oh, I did not notice that `^R` restarts the System. That’s good enough for me, I believe. I wonder if that also means it restarts any animation… me tries.

**Comment by andygill** [comment]
^R is the browser reload command.

**Comment by andygill** [comment]
@jtdawso - Can you look into getting remote monad pushed to hackage; and @roboguy13 - can yoy look into getting blank canvas working with hackage packages.

**Comment by nomeata** [comment]
I’m happy with this situation.
