### ISSUE TITLE
Provide `IO a -> Canvas a`

### ISSUE THREAD

**Issue by nomeata** [ku-fpg/blank-canvas#81]
This is obviously not something to be exported by the main module, but for some tasks, it is necessary to do (local) IO in the Canvas monad.

Would it be possible to implement `ioToCanvas :: IO a -> Canvas a`, exported via some `.Internal` module maybe?

**Comment by nomeata** [comment]
Things I want to do here are: 

 * Waiting for a certain amount of time
 * Getting the current time
 * Reading and writing MVars

The former two might not be needed if #18 is implemented, but in general, there is always a chance that something is missing from a too-abstract interface.

**Comment by nomeata** [comment]
Nevermind, I think I am being stupid here.

**Comment by andygill** [comment]
We had this at some point. There are pros and cons. We decided to remove it, because it clarifies what Canvas can actually do - talk to the browser.
