### ISSUE TITLE
doesn't compile on 9.6.1

### ISSUE THREAD

**Issue by GeorgeCo** [ku-fpg/blank-canvas#97]
bllank-canvas doesn't compile on 9.6.1
perhaps all it needs is some version limits bumped as it compiles with --allow-new
```
 cabal install --lib blank-canvas
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.1
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.1
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: aeson-2.1.2.1 (user goal)
[__1] trying: base-4.18.0.0/installed-4.18.0.0 (user goal)
[__2] next goal: blank-canvas (user goal)
[__2] rejecting: blank-canvas-0.7.3 (conflict:
base==4.18.0.0/installed-4.18.0.0, blank-canvas => base>=4.7 && <4.18)
```

**Comment by RyanGlScott** [comment]
I've applied [a Hackage revision](https://hackage.haskell.org/package/blank-canvas-0.7.3/revisions/) (see also da4120a1c6d4cb4e3145e98dd0c87d607afdb3a4) that should allow `blank-canvas` to build with GHC 9.6.1. Please re-open this issue if you experience any other difficulties.

**Comment by GeorgeCo** [comment]
@RyanGlScott Thx! BTW this is very impressive software!
