### ISSUE TITLE
support for scotty-0.20

### ISSUE THREAD

**Issue by jkachmar** [ku-fpg/blank-canvas#98]
## Description

[`scotty`](https://hackage.haskell.org/package/scotty) has been updated to [`0.20.0`](https://hackage.haskell.org/package/scotty-0.20/changelog).

**Comment by RyanGlScott** [comment]
I've uploaded [`blank-canvas-0.7.4`](https://hackage.haskell.org/package/blank-canvas-0.7.4) to Hackage with a fix.
